name: Beancount SQL Queries
description: Sample queries for the SQL-like Beancount Query Language. Contribute your own by creating an issue or submitting a pull request.

destination: ./_gen/

exclude: ["css/_scss",]
permalink: /query/:title.html

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

sass:
    sass_dir: css/_scss
    style: expanded
